# Generated by Django 4.2 on 2023-05-19 09:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLoggingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', error_messages=False, help_text='<small class="text-muted">CharField [0, 100]</small><hr><br>', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)], verbose_name='Имя пользователя')),
                ('text', models.TextField(blank=True, db_index=True, default='', error_messages=False, help_text='<small class="text-muted">TextField [0, 3000]</small><hr><br>', max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(3000)], verbose_name='Действие')),
                ('created', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">DateTimeField</small><hr><br>', null=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Лог Действий',
                'verbose_name_plural': 'Логи Действий',
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='loggingmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='loggingmodel',
            name='path',
            field=models.SlugField(blank=True, default='', error_messages=False, help_text='<small class="text-muted">SlugField [0, 300]</small><hr><br>', max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(300)], verbose_name='Путь'),
        ),
    ]
