# Generated by Django 4.2 on 2023-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_salary', '0003_activityloggingmodel_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityloggingmodel',
            name='myself',
            field=models.BooleanField(blank=True, default=False, error_messages=False, help_text='<small class="text-muted">BooleanField</small><hr><br>', verbose_name='Сам совершил?'),
        ),
    ]
