# Generated by Django 4.2 on 2023-05-19 10:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_salary', '0004_activityloggingmodel_myself'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListIPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, default=None, error_messages=False, help_text='<small class="text-muted">ip[0, 300]</small><hr><br>', null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(300)], verbose_name='Ip адрес')),
                ('path', models.SlugField(blank=True, default='', error_messages=False, help_text='<small class="text-muted">SlugField [0, 300]</small><hr><br>', max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(300)], verbose_name='Путь')),
                ('created', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, error_messages=False, help_text='<small class="text-muted">DateTimeField</small><hr><br>', null=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Черный IP',
                'verbose_name_plural': 'Черный Лист IP',
                'ordering': ('-created',),
            },
        ),
    ]
